platform :ios, '9.0'
use_frameworks!

target 'awtarika' do
    pod 'Alamofire', '~> 4.3'
    pod 'AlamofireImage', '~> 3.1'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Google/Analytics'
    pod 'iOSLogEntries'
    pod 'KDEAudioPlayer', :git => 'https://github.com/delannoyk/AudioPlayer', :branch => 'master'
    pod 'ActiveLabel'
end
