platform :ios, '9.0'
use_frameworks!

target 'awtarika' do
    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireImage', '~> 2.0'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'KDEAudioPlayer'
end
